---
- name: "Netbox DNS Record"
  hosts: localhost
  vars:
    record_name: "ansible-test"
    zone: "int.vpulse.network"

    credentials: &credentials
      netbox_url: "{{ lookup('ansible.builtin.env', 'NETBOX_API') }}"
      netbox_token: "{{ lookup('ansible.builtin.env', 'NETBOX_TOKEN') }}"

  tasks:
    - name: "Test nb_dns_record module"
      chaeynz.netbox_dns.netbox_nb_dns_record:
        <<: *credentials
        data:
          name: "{{ record_name }}"
          zone: "{{ zone }}"
          type: "A"
          value: "203.0.113.0"
          status: inactive
          ttl: 113
          description: "Funny description"
          tags:
            - some_tag
          disable_ptr: true
          tenant: "{{ tenant | default(omit) }}"
        state: "{{ _state | default('present') }}"
